### PR TITLE
Removed broken static svg link

### LINKED ISSUE #61: Broken link
Theres a broken link on the documentation index page

https://github.com/chaostoolkit/chaostoolkit-documentation/blob/master/sources/index.md

### PR DESCRIPTION
**Pull request by russmiles**
Possibly just for now...

Closes #61

Signed-off-by: Russ Miles <russ@russmiles.com>

### CODE REVIEW

**Comment by dmartin35** [comment]
isn't it supposed to be the same image as on the chaostoolit.org main page ? 
https://chaostoolkit.org/static/chaostoolkit-schema-835b2c8a4c19fa8c10d0ae2b43bbb69a.svg

If so, we might duplicate it on this repo, as the hash of the image might change when re-deploying the website ?

**Comment by Lawouach** [comment]
The trick is indeed that the source image changes everytime the www website is rebuilt. Three options:

* we remove it (this PR)
* we make a static version that is comitted once and for all in this repo
* we update this repo everytime the other repo is rebuild (harder and little value since the image never changes)

**Comment by russmiles** [comment]
I'm happy with a static version to be generated and checked in, if that's straightforward? I'm not clear how to do it.

**Comment by Lawouach** [comment]
me neither :) probably need to ping @mperrien tomorrow

**Comment by SuperKogito** [comment]
I think broken links are a common issue and a radical solution to this problem is automatically checking and reporting them. Luckily the new GitHub actions and  workflows help with that. I recently wrote an action that just does that. [URLs-checker](https://github.com/marketplace/actions/urls-checker) will check and report broken links, which is useful to spot similar issues to this one.

**Comment by ciaranevans** [comment]
@Lawouach good to ☠️ ?

**Comment by Lawouach** [comment]
I think we can indeed.

**Pull request closed without merging**
