### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by born4new**
If using vscode, the spellcheck extension is pretty handy :).

### CODE REVIEW

**Comment by Lawouach** [comment]
Thanks so much @born4new for spotting and fixing them :)

Before we could merge, could you ensure you can sign the commit to abide with our DCO?

Thanks!

**Comment by Lawouach** [comment]
Thanks!

That's interesting because you have indeed signed (and thank you for that) but your client doesn't seem to add the `Signed-off-by: username <email>` bit to the commit message you pushed. I had not seen that yet.

This is why our DCO checker still complains. i'm happy to merge away on the documetation as-is considering you have signed anyway.

But in the future, do you feel you could add such token to make it happier? As per https://github.com/probot/dco

**Comment by born4new** [comment]
Hopefully it should be better now...

I was just missing the `-s` flag when creating the commit. I will make that automatic :)

**Comment by Lawouach** [comment]
Thanks a lot for that!

**Pull request merged**
